### ISSUE TITLE
track lost about the NewTsukubaStereoDataset

### ISSUE THREAD

**Issue by chubukeji** [felixchenfy/Monocular-Visual-Odometry#12]
hello, I use ORB-SLAM2 run the NewTsukubaStereoDataset, but it easily fails to track due to the rapid rotation of the camera lens，Have you encountered this situation？

**Comment by felixchenfy** [comment]
It probably will... The performance of this work is so poor that it can only be used under limited circumstances and used as a student's course project. 

Sorry about that :(

**Comment by chubukeji** [comment]
thanks
