### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by lema18** [felixchenfy/Monocular-Visual-Odometry#4]
In vo.cpp at line 302 at poseEstimationPnP function.. why do you use
curr_->T_w_c_ = transRt2T(R, t).inv();
instead of
curr_->T_w_c_ =ref_->T_w_c * transRt2T(R, t).inv();
?

**Comment by felixchenfy** [comment]
@lema18 PnP uses 3D world points and their projections on the camera to compute the camera pose wrt to the world. So here R and t is the relation between world frame and camera frame.  
 My comment on line 262 is wrong. Sorry about that.

**Comment by lema18** [comment]
thanks
