### ISSUE TITLE
Bundle adjustment bug

### ISSUE THREAD

**Issue by fredO13** [felixchenfy/Monocular-Visual-Odometry#5]
Hey,

I think there's a bug in **_void VisualOdometry::callBundleAdjustment()_**

You're looping on the last 5 frames and there's a **_continue_** if the frame has less than 3 points in the map. Right below the continue are two **_push_back_** on _**v_pts_2d**_ and **_v_pts_to_3d_** that are not done when _continue_ happen, but the index is still **_ith_frame_** which may not exist in case _continue_ was called before.

You may want to select the appropriate frames (the last 5 frames with enough points in the map) before calling the existing code, removing the continue.

**Comment by ouyangandy** [comment]
So how do you feel about fixing it? I am confused about what you said.

**Comment by felixchenfy** [comment]
@fredO13 Hi, really appreciate it for reading my code so carefully and pointing out the bugs.

I've changed:
```

            v_pts_2d[ith_frame].push_back(&(frame->keypoints_[kpt_idx].pt));
            v_pts_2d_to_3d_idx[ith_frame].push_back(mappt_idx);
```

To:
```
            v_pts_2d.back().push_back(&(frame->keypoints_[kpt_idx].pt));
            v_pts_2d_to_3d_idx.back().push_back(mappt_idx);
```

@ouyangandy
